name: DevSecOps Pipeline

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: [self-hosted, DEVSEC]

    env:
      IMAGE_NAME: asivanan/2048_game

    steps:

    # 1️⃣ Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2️⃣ Setup Node.js
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # 3️⃣ Install Dependencies
    - name: Install Dependencies
      run: npm install

    # 4️⃣ SonarQube Scan
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # 5️⃣ Quality Gate Check
    - name: SonarQube Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # 6️⃣ Trivy File System Scan
    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        output: 'trivyfs.txt'

    # 7️⃣ Login to DockerHub
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 8️⃣ Build Docker Image
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    # 9️⃣ Push Docker Image
    - name: Push Docker Image
      run: docker push $IMAGE_NAME:latest

    # 🔟 Trivy Image Scan
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.IMAGE_NAME }}:latest'
        output: 'trivy-image.txt'

    # 1️⃣1️⃣ Deploy to Docker (Optional)
    - name: Run Container
      run: |
        docker rm -f 2048 || true
        docker run -d --name 2048 -p 3000:3000 $IMAGE_NAME:latest

    # 1️⃣2️⃣ Setup Kubeconfig
    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    # 1️⃣3️⃣ Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
